# Generated by Django 2.1.13 on 2019-11-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('giftTransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('amountDeducting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestTransactions',
            fields=[
                ('testerId', models.AutoField(primary_key=True, serialize=False)),
                ('usertest', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('received', models.IntegerField()),
                ('givenBucket', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.Users'),
        ),
    ]
