# Generated by Django 2.1.13 on 2019-11-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemTransactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('points_redeemed', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('admin', models.BooleanField()),
                ('points_left', models.IntegerField()),
                ('points_received', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='redeemtransactions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemUser', to='points.Users'),
        ),
        migrations.AddField(
            model_name='pointtransactions',
            name='recipient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivingUser', to='points.Users'),
        ),
        migrations.AddField(
            model_name='pointtransactions',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendingUser', to='points.Users'),
        ),
    ]
