# Generated by Django 2.1.13 on 2019-11-15 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('giftTransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('amountDeducting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PointTransactions',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionDate', models.DateTimeField(auto_now_add=True)),
                ('pointAmount', models.IntegerField()),
                ('message', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('received', models.IntegerField()),
                ('givenBucket', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pointtransactions',
            name='userGiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givingUser', to='points.Users'),
        ),
        migrations.AddField(
            model_name='pointtransactions',
            name='userReceiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivingUser', to='points.Users'),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.Users'),
        ),
    ]
