# Generated by Django 2.1.13 on 2019-11-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransaction',
            name='transactionDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
