runtime: python37

entrypoint: gunicorn -b:8080 dbmsite.wsgi

# [START python37 cloudsql config]
env_variables:
  CLOUD_SQL_USERNAME: ####
  CLOUD_SQL_PASSWORD: ####
  CLOUD_SQL_DATABASE_NAME: ####
  CLOUD_SQL_CONNECTION_NAME: ####
# [END python37 cloudsql config]
